name: Run script.sh on sources.json change

on:
  push:
    paths:
      - 'sources.json'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run script.sh
        run: |-
          chmod +x script.sh
          ./script.sh
      - name: Commit and push changes
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update feeds: ${timestamp}" || exit 0
          git push
